//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack.GameService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerList", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWcfService.Model")]
    [System.SerializableAttribute()]
    public partial class PlayerList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, BlackJack.GameService.Player> PlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, BlackJack.GameService.Player> Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWcfService.Model")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackJack.GameService.Ccard[] CardListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackJack.GameService.Ccard[] CardList {
            get {
                return this.CardListField;
            }
            set {
                if ((object.ReferenceEquals(this.CardListField, value) != true)) {
                    this.CardListField = value;
                    this.RaisePropertyChanged("CardList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GamePlayer", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWcfService.Model")]
    [System.SerializableAttribute()]
    public partial class GamePlayer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SomeArtibute1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SomeAtribute2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SomeArtibute1 {
            get {
                return this.SomeArtibute1Field;
            }
            set {
                if ((this.SomeArtibute1Field.Equals(value) != true)) {
                    this.SomeArtibute1Field = value;
                    this.RaisePropertyChanged("SomeArtibute1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SomeAtribute2 {
            get {
                return this.SomeAtribute2Field;
            }
            set {
                if ((this.SomeAtribute2Field.Equals(value) != true)) {
                    this.SomeAtribute2Field = value;
                    this.RaisePropertyChanged("SomeAtribute2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ccard", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWcfService.Model")]
    [System.SerializableAttribute()]
    public partial class Ccard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackJack.GameService.Fase nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackJack.GameService.Suit suitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackJack.GameService.Fase name {
            get {
                return this.nameField;
            }
            set {
                if ((this.nameField.Equals(value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int points {
            get {
                return this.pointsField;
            }
            set {
                if ((this.pointsField.Equals(value) != true)) {
                    this.pointsField = value;
                    this.RaisePropertyChanged("points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackJack.GameService.Suit suit {
            get {
                return this.suitField;
            }
            set {
                if ((this.suitField.Equals(value) != true)) {
                    this.suitField = value;
                    this.RaisePropertyChanged("suit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fase", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWcfService.Model")]
    public enum Fase : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deuce = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Four = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Five = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Six = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seven = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eight = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nine = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ten = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jack = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queen = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        King = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ace = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zero = 255,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Suit", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWcfService.Model")]
    public enum Suit : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Heart = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Club = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diamond = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spade = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IGameService", CallbackContract=typeof(BlackJack.GameService.IGameServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Login", ReplyAction="http://tempuri.org/IGameService/LoginResponse")]
        int Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Login", ReplyAction="http://tempuri.org/IGameService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string login, string pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Registration", ReplyAction="http://tempuri.org/IGameService/RegistrationResponse")]
        int Registration(string login, string pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Registration", ReplyAction="http://tempuri.org/IGameService/RegistrationResponse")]
        System.Threading.Tasks.Task<int> RegistrationAsync(string login, string pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Logout", ReplyAction="http://tempuri.org/IGameService/LogoutResponse")]
        void Logout(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Logout", ReplyAction="http://tempuri.org/IGameService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/UpdatePlayerList")]
        void UpdatePlayerList(BlackJack.GameService.PlayerList players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/BattleStarted")]
        void BattleStarted(BlackJack.GameService.GamePlayer[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/PlayerMoved")]
        void PlayerMoved(BlackJack.GameService.GamePlayer player);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : BlackJack.GameService.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<BlackJack.GameService.IGameService>, BlackJack.GameService.IGameService {
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int Login(string login1, string pasword) {
            return base.Channel.Login(login1, pasword);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string login, string pasword) {
            return base.Channel.LoginAsync(login, pasword);
        }
        
        public int Registration(string login, string pasword) {
            return base.Channel.Registration(login, pasword);
        }
        
        public System.Threading.Tasks.Task<int> RegistrationAsync(string login, string pasword) {
            return base.Channel.RegistrationAsync(login, pasword);
        }
        
        public void Logout(int id) {
            base.Channel.Logout(id);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(int id) {
            return base.Channel.LogoutAsync(id);
        }
    }
}
